services:
  python-text-ml:
    build:
      context: ./python-text-ml
    container_name: python-text-ml
    ports:
      - "6000:6000"
    environment:
      CLAP_CACHE_DIR: /app/.cache/clap
      HF_HOME: /app/.cache/clap
      TORCH_HOME: /app/.cache/clap
      XDG_CACHE_HOME: /app/.cache/clap
    volumes:
      - clap_cache:/app/.cache/clap
    restart: unless-stopped

volumes:
  clap_cache: